#!/bin/bash
#
#  "sysd-add" script by furryfixer which is a shortcut to
#  BOTH enable AND start systemd service for $1 with an extra check
#  to ensure root access and operand is given.

if [ "$EUID" -ne 0 ]; then
	echo "You must be ROOT for this command to work"
	exit 1
fi
if [ -z "$1" ] || [ ! -z "$2" ]; then       
	echo "Syntax error. One and only one operand expected. "\""sysd-add A"\"
	exit 1
fi
sv_loaded=$(systemctl is-enabled $1)
if [[ $sv_loaded = "not-found" ]]; then
	echo "Error. A Service(unit) file is not found for "\"$1\""
    No changes were made."
	exit 1
fi
if [[ $sv_loaded = "enabled" ]]; then
	echo \"$1\"" was already enabled. If not running,
    it was started."
fi
systemctl enable $1 || exit 1
systemctl start $1 || exit 1
echo \"$1\"" service successfully enabled and started"
