#!/bin/bash
#
#  "sysd-rm" script by furryfixer which is a shortcut that
#  does BOTH stopping AND disabling systemd service $1.
#  There is an extra check to ensure root access and that
#  only one operand is given.

if [ "$EUID" -ne 0 ]; then
	echo "You must be ROOT for this command to work"
	exit 1
fi
if [ -z "$1" ] || [ ! -z "$2" ]; then       
        echo "Syntax error. One and only one operand expected. "\""sysd-rm A"\"
        exit 1
fi
sv_loaded=$(systemctl is-enabled $1)
if [[ $sv_loaded = "not-found" ]]; then
	echo "Error. A Service(unit) file is not found for "\"$1\""
    No changes were made."
	exit 1
fi
systemctl stop $1 || exit 1
systemctl disable $1 || exit 1
if [[ ! $sv_loaded = "enabled" ]]; then
	echo \"$1\"" was already disabled. If running,
    it was stopped."
fi
echo \"$1\"" was succsesfully stopped and disabled."
